=== mdsamdsa/zigbee-gw-client/data/profiles/zigbee.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xml="http://www.w3.org/XML/1998/namespace">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/03/xml.xsd"/>

	<xs:complexType name="clusterType">
		<xs:sequence>
			<xs:element name="attribute" type="attributeType" maxOccurs="30" minOccurs="0"/>
			<xs:element name="command" type="commandType" maxOccurs="30" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="sideType">
		<xs:sequence>
			<xs:element name="clusterRef" type="clusterRefType" maxOccurs="30" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="deviceType">
		<xs:sequence>
			<xs:element name="server" type="sideType" maxOccurs="1" minOccurs="0"/>
			<xs:element name="client" type="sideType" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="clusterRefType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="mandatory" type="xs:boolean" use="required"/>
	</xs:complexType>

	<xs:complexType name="rangeType">
		<xs:attribute name="from" type="xs:string" use="required"/>
		<xs:attribute name="to" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="enumType">
		<xs:sequence>
			<xs:element name="value" type="valueType" maxOccurs="30" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="paramType">
		<xs:sequence>
			<xs:element name="range" type="rangeType" maxOccurs="30" minOccurs="0"/>
			<xs:element name="enum" type="enumType" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="valueType">
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="attributeType">
		<xs:sequence>
			<xs:element name="range" type="rangeType" maxOccurs="30" minOccurs="0"/>
			<xs:element name="enum" type="enumType" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="xs:string" use="required"/>
		<xs:attribute name="access" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="r"/>
					<xs:enumeration value="w"/>
					<xs:enumeration value="rw"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="default" type="xs:string"/>
		<xs:attribute name="mandatory" type="xs:boolean" use="required"/>
	</xs:complexType>

	<xs:complexType name="commandType">
		<xs:sequence>
			<xs:element name="param" type="paramType" maxOccurs="30" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="mandatory" type="xs:boolean" use="required"/>
	</xs:complexType>

	<xs:complexType name="profileType">
		<xs:sequence>
			<xs:element name="clusters" maxOccurs="1" minOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="cluster" type="clusterType" maxOccurs="unbounded" minOccurs="0"/>
					</xs:sequence>
					<xs:attribute ref="xml:base"/>
				</xs:complexType>
			</xs:element >
			<xs:element name="device" type="deviceType" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:element name="profiles">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="profile" type="profileType" maxOccurs="30" minOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="datatypeType">
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="required"/>
		<xs:attribute name="length" type="xs:nonNegativeInteger"/>
		<xs:attribute name="invalid" type="xs:string"/>
	</xs:complexType>

	<xs:element name="datatypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="datatype" type="datatypeType" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mdsamdsa/zigbee-gw-client/data/profiles/type.xml
<?xml version="1.0" encoding="utf-8"?>
<datatypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zigbee.xsd">
    <datatype id="0x00" name="nodata" description="No data" length="0"/>
    <datatype id="0x08" name="data8" description="8-bit data" length="1"/>
    <datatype id="0x09" name="data16" description="16-bit data" length="2"/>
    <datatype id="0x0a" name="data24" description="24-bit data" length="3"/>
    <datatype id="0x0b" name="data32" description="32-bit data" length="4"/>
    <datatype id="0x0c" name="data40" description="40-bit data" length="5"/>
    <datatype id="0x0d" name="data48" description="48-bit data" length="6"/>
    <datatype id="0x0e" name="data56" description="56-bit data" length="7"/>
    <datatype id="0x0f" name="data64" description="64-bit data" length="8"/>
    <datatype id="0x10" name="boolean" description="Boolean" length="1" invalid="0xff"/>
    <datatype id="0x18" name="bmp8" description="8-bit bitmap" length="1"/>
    <datatype id="0x19" name="bmp16" description="16-bit bitmap" length="2"/>
    <datatype id="0x1a" name="bmp24" description="24-bit bitmap" length="3"/>
    <datatype id="0x1b" name="bmp32" description="32-bit bitmap" length="4"/>
    <datatype id="0x1c" name="bmp40" description="40-bit bitmap" length="5"/>
    <datatype id="0x1d" name="bmp48" description="48-bit bitmap" length="6"/>
    <datatype id="0x1e" name="bmp56" description="56-bit bitmap" length="7"/>
    <datatype id="0x1f" name="bmp64" description="64-bit bitmap" length="8"/>
    <datatype id="0x20" name="uint8" description="Unsigned 8-bit integer" length="1" invalid="0xff"/>
    <datatype id="0x21" name="uint16" description="Unsigned 16-bit integer" length="2" invalid="0xffff"/>
    <datatype id="0x22" name="uint24" description="Unsigned 24-bit integer" length="3" invalid="0xffffff"/>
    <datatype id="0x23" name="uint32" description="Unsigned 32-bit integer" length="4" invalid="0xffffffff"/>
    <datatype id="0x24" name="uint40" description="Unsigned 40-bit integer" length="5" invalid="0xffffffffff"/>
    <datatype id="0x25" name="uint48" description="Unsigned 48-bit integer" length="6" invalid="0xffffffffffff"/>
    <datatype id="0x26" name="uint56" description="Unsigned 56-bit integer" length="7" invalid="0xffffffffffffff"/>
    <datatype id="0x27" name="uint64" description="Unsigned 64-bit integer" length="8" invalid="0xffffffffffffffff"/>
    <datatype id="0x28" name="int8" description="Signed 8-bit integer" length="1" invalid="0x80"/>
    <datatype id="0x29" name="int16" description="Signed 16-bit integer" length="2" invalid="0x8000"/>
    <datatype id="0x2a" name="int24" description="Signed 24-bit integer" length="3" invalid="0x800000"/>
    <datatype id="0x2b" name="int32" description="Signed 32-bit integer" length="4" invalid="0x80000000"/>
    <datatype id="0x2c" name="int40" description="Signed 40-bit integer" length="5" invalid="0x8000000000"/>
    <datatype id="0x2d" name="int48" description="Signed 48-bit integer" length="6" invalid="0x800000000000"/>
    <datatype id="0x2e" name="int56" description="Signed 56-bit integer" length="7" invalid="0x80000000000000"/>
    <datatype id="0x2f" name="int64" description="Signed 64-bit integer" length="8" invalid="0x8000000000000000"/>
    <datatype id="0x30" name="enum8" description="8-bit enumeration" length="1" invalid="0xff"/>
    <datatype id="0x31" name="enum16" description="16-bit enumeration" length="2" invalid="0xffff"/>
    <datatype id="0x38" name="semi" description="Semi-precision" length="2"/>
    <datatype id="0x39" name="float" description="Single precision" length="4"/>
    <datatype id="0x3a" name="double" description="Double precision" length="8"/>
    <datatype id="0x41" name="ostring" description="Octet string" invalid="0xff"/>
    <datatype id="0x42" name="cstring" description="Character string" invalid="0xff"/>
    <datatype id="0x43" name="lostring" description="Long octet string" invalid="0xffff"/>
    <datatype id="0x44" name="lcstring" description="Long character string" invalid="0xffff"/>
    <datatype id="0x48" name="array" description="Array" invalid="0xffff"/>
    <datatype id="0x4c" name="struct" description="Structure" invalid="0xffff"/>
    <datatype id="0x50" name="set" description="Set" invalid="0xffff"/>
    <datatype id="0x51" name="bag" description="Bag" invalid="0xffff"/>
    <datatype id="0xe0" name="time" description="Time of day" length="4" invalid="0xffffffff"/>
    <datatype id="0xe1" name="date" description="Date" length="4" invalid="0xffffffff"/>
    <datatype id="0xe2" name="utc" description="UTCTime" length="4" invalid="0xffffffff"/>
    <datatype id="0xe8" name="cid" description="Cluster ID" length="2" invalid="0xffff"/>
    <datatype id="0xe9" name="aid" description="Attribute ID" length="2" invalid="0xffff"/>
    <datatype id="0xea" name="oid" description="BACnet OID" length="4" invalid="0xffffffff"/>
    <datatype id="0xf0" name="ieee" description="IEEE address" length="8" invalid="0xffffffffffffffff"/>
    <datatype id="0xf1" name="seckey" description="128-bit security key" length="16"/>
</datatypes>

=== mdsamdsa/zigbee-gw-client/data/profiles/zll.xml
<?xml version="1.0" encoding="utf-8"?>

<profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zigbee.xsd">
    <profile id="0xc05e" name="ZigBee Light Link Profile">
        <xi:include href="zcl.xml" xmlns:xi="http://www.w3.org/2001/XInclude"/>
        <device id="0x0000" name="On/Off Light">
            <server>
                <clusterRef name="Basic" mandatory="true"/>
                <clusterRef name="Identify" mandatory="true"/>
                <clusterRef name="On/Off" mandatory="true"/>
                <clusterRef name="Scenes" mandatory="true"/>
                <clusterRef name="Groups" mandatory="true"/>
            </server>
        </device>
        <device id="0x0100" name="Dimmable Light">
            <server>
                <clusterRef name="Basic" mandatory="true"/>
                <clusterRef name="Identify" mandatory="true"/>
                <clusterRef name="On/Off" mandatory="true"/>
                <clusterRef name="Level Control" mandatory="true"/>
                <clusterRef name="Scenes" mandatory="true"/>
                <clusterRef name="Groups" mandatory="true"/>
            </server>
        </device>
        <device id="0x0200" name="Color Light">
            <server>
                <clusterRef name="Basic" mandatory="true"/>
                <clusterRef name="Identify" mandatory="true"/>
                <clusterRef name="On/Off" mandatory="true"/>
                <clusterRef name="Level Control" mandatory="true"/>
                <clusterRef name="Color Control" mandatory="true"/>
                <clusterRef name="Scenes" mandatory="true"/>
                <clusterRef name="Groups" mandatory="true"/>
            </server>
        </device>
        <device id="0x0210" name="Ext Color Light">
            <server>
                <clusterRef name="Basic" mandatory="true"/>
                <clusterRef name="Identify" mandatory="true"/>
                <clusterRef name="On/Off" mandatory="true"/>
                <clusterRef name="Level Control" mandatory="true"/>
                <clusterRef name="Color Control" mandatory="true"/>
                <clusterRef name="Scenes" mandatory="true"/>
                <clusterRef name="Groups" mandatory="true"/>
            </server>
        </device>
    </profile>
</profiles>
